name: Run Python script and release folder

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg zip
        pip3 install -r requirements.txt
    - name: Run script and zip folder
      run: |
        python3 main.py
        cd MonsterSiren
        zip -r ../MonsterSiren.zip .
        cd ..
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0-$(date '+%Y-%m-%d')
        release_name: Release $(date '+%Y-%m-%d')
        draft: false
        prerelease: false
    - name: Upload folder
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: MonsterSiren.zip
        asset_name: MonsterSiren.zip
        asset_content_type: application/zip
